// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.1.0.
// **********************************************************************

var TRom = require('./NodeJsComm.js').TRom;
module.exports.TRom = TRom;

TRom.NodeJsCommImp.prototype.initialize = function ( ) {

}

TRom.NodeJsCommImp.prototype.test = function (current) {

}

TRom.NodeJsCommImp.prototype.getall = function (current, stUser, stResult) {
  console.log('stUser', stUser)

  stResult.id = 10000
  stResult.iLevel = 10001

  current.sendResponse(200, stResult)
}

TRom.NodeJsCommImp.prototype.getUsrName = function (current, sUsrName, sValue1, sValue2) {

}

TRom.NodeJsCommImp.prototype.secRequest = function (current, binRequest, binResponse) {

}


